Updated the APIs to be more swifty
nodes-ios/Codemine pull request #34
Opened 2016-09-25 19:47 UTC by chriscombs

In line with the changes to many native APIs in swift 3.0. Some of them were fairly straightforward, but would like feedback on some of the more drastic changes.

2016-09-25 19:54 UTC, nickskull commented on Codemine/Extensions/String+Range.swift
> +    private func contains(_ range: Range<Index>) -> Bool {
I think we should make the parameter name non optional, otherwise it's a bit unclear.

EDIT: Probably not, the guidelines are fine with this :P

2016-09-25 19:55 UTC, nickskull commented on Codemine/Extensions/UIImage+Utilities.swift
> +    public class func from(color: UIColor, size: CGSize, cornerRadius: CGFloat) -> UIImage? {
Is it too crazy to make this a convenience initialiser instead of a class function? Think it would make more sense.

2016-09-25 19:57 UTC, nickskull commented on Codemine/Extensions/UIView+Utilities.swift
> +    public static func fromNib<T>(_ name:String) -> T? {
What about `from<T>(nibWithName: String) -> T?`? Feels a bit more expressive.

2016-09-25 20:00 UTC, nickskull commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversedSize: CGRect {
This sounds a bit odd, as if it was return a size instead of `CGRect`. Is `reverseSized` grammatically incorrect and/or too weird? :D

2016-09-25 20:01 UTC, nickskull commented on Codemine/Extensions/String+Range.swift
> +    public func rangeFrom(string: String, toString: String, searchType: RangeSearchType = .leftToRight,  inRange: Range<Index>? = nil) -> Range<Index>? {
I am pretty sure this one should be `range(from fromString: String, to toString: String, ....` :)

2016-09-25 20:02 UTC, dominik-hadl requested changes

2016-12-16 13:01 UTC, mariusc commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversedSize: CGRect {
What about reversingSize? That seems to be similar to the examples here https://github.com/apple/swift-evolution/blob/master/proposals/0005-objective-c-name-translation.md `func bezierPathByReversingPath() -> UIBezierPath` -> `func reversing() -> UIBezierPath`

2016-12-16 13:05 UTC, mariusc commented
@chriscombs  @nickskull What's the status on this PR? Should I make those changes and merge to the swift-3.0 branch, so we can take it further from there?

2016-12-16 13:55 UTC, nickskull commented
@mariusc Yeah, I think that would be the best, if @chriscombs agrees.

2016-12-21 15:06 UTC, mariusc commented
@nickskull @chriscombs Can you guys look over this and give a bit of feedback? Or merge the PR? 😄

2016-12-21 15:21 UTC, dominik-hadl requested changes

2016-12-21 15:21 UTC, nickskull commented on Codemine/Extensions/CGRect+Utilities.swift
>          return CGRect(origin: self.origin, size: CGSize(width: self.height, height: self.width))
Can we lose the `self`s here? :D

2016-12-21 15:21 UTC, nickskull commented on Codemine/Extensions/NSURL+AssetSize.swift
> +		case standard	= "default"
This should be kept as default, you can do this by writing `default` in backticks.

2016-12-21 15:26 UTC, chriscombs commented
Wow I don't even remember starting this PR 😄

2016-12-21 15:30 UTC, chriscombs commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversingSize: CGRect {
Should change this to `reversedSize`

2016-12-21 15:30 UTC, chriscombs commented on Codemine/Extensions/NSURL+AssetSize.swift
> +		case standard	= "default"
👍

2016-12-21 15:31 UTC, mariusc commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversingSize: CGRect {
It was `reversedSize`, but then this discussion happened https://github.com/nodes-ios/Codemine/pull/34#discussion_r80390518. But I can change it back to `reversedSize` if you think it's better

2016-12-21 15:33 UTC, chriscombs commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversingSize: CGRect {
Oh, I missed that. I guess it's fine then, if that's what Apple does. Also, why is that BezierPath thing a func and not a var?

2016-12-21 15:35 UTC, nickskull commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversingSize: CGRect {
You're the native speaker @chriscombs, so if you think it should be different let's do it that way. Apple is being classic in not obeying their own rules :D

2016-12-21 15:55 UTC, chriscombs commented on Codemine/Extensions/CGRect+Utilities.swift
> +	public var reversingSize: CGRect {
I think you're right in that `reversedSize` implies that it returns the size and not the rect.

2016-12-21 20:29 UTC, dominik-hadl approved these changes

2016-12-21 20:29 UTC, merged